version: 2
updates:
- package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
    open-pull-requests-limit: 100