environment = "test"
cluster_name = "repo"
repo_name = "prm-mhs-infra"
mhs_state_table_read_capacity = 5
mhs_state_table_write_capacity = 5
mhs_sync_async_table_read_capacity = 5
mhs_sync_async_table_write_capacity = 5
elasticache_node_type               = "cache.t3.micro"
setup_public_dns_record = "true"
mhs_inbound_service_minimum_instance_count = 1
recipient_ods_code                  = "B86041" # Not enforced in opentest

spine_cidr = "0.0.0.0/0" # FIXME: narrow down to only the services that we talk to
sds_port                            = 636
spineroutelookup_service_sds_url    = "ldaps://ldap.nis1.national.ncrs.nhs.uk:636" # MUST BE AN IP in dev environment
mhs_forward_reliable_endpoint_url  = "https://msg.intspineservices.nhs.uk/reliablemessaging/reliablerequest"
mhs_asynchronous_reliable_endpoint_url  = "https://msg.intspineservices.nhs.uk/reliablemessaging/reliablerequest"
mhs_synchronous_endpoint_url = "https://msg.intspineservices.nhs.uk/sync-service"
spineroutelookup_service_search_base = "ou=services,o=nhs"
spineroutelookup_service_disable_sds_tls = "False"
mhs_log_level                       = "DEBUG"
mhs_route_service_maximum_instance_count = 2
mhs_route_service_minimum_instance_count = 1
mhs_outbound_service_maximum_instance_count = 2
mhs_outbound_service_minimum_instance_count = 1
mhs_resynchroniser_max_retries="20"
mhs_resynchroniser_interval="1"
spine_org_code="YES"
is_public_nlb = true
mhs_vpc_cidr_block = "10.239.68.0/23"
mhs_outbound_lookup_method = "SDS_API"
enable_sds_fhir_api = true
