format_version: 4
common:
  repo_plan: &repo_plan
    - resources:
        - docker
    - artifacts:
        - build:
            source: terraform/deployment.tfplan
            destination: terraform/
    - tasks:
        - exec:
            command: /bin/bash
            working_directory: prm-mhs-infra
            arguments:
              - -c
              - ./tasks tf_plan_repo create

  repo_deploy_tasks: &repo_deploy_tasks
    - resources:
        - docker
    tasks:
      - fetch:
          stage: plan_prod
          job: plan
          source: terraform/deployment.tfplan
          destination: terraform/
          is_file: yes
      - exec:
          command: /bin/bash
          working_directory: prm-mhs-infra
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          working_directory: prm-mhs-infra
          arguments:
            - -c
            - ./tasks wait_ecs repo

  test_harness_deploy_tasks: &test_harness_deploy_tasks
    - fetch:
        pipeline: prm-repo-mhs
        stage: build_docker
        job: outbound
        source: imagerc/outbound
        destination: prm-mhs-infra/imagerc
        is_file: true
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks tf_plan_test_harness create
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks tf_apply
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks wait_ecs test_harness

pipelines:
  "prm-mhs-infra.dev":
    group: mhs
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      mhs_docker:
        pipeline: prm-repo-mhs
        stage: build_docker
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: deploy_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - fetch:
                pipeline: prm-repo-mhs
                stage: build_docker
                job: outbound
                source: imagerc/outbound
                destination: prm-mhs-infra/imagerc
                is_file: true
            - exec:
                command: /bin/bash
                working_directory: prm-mhs-infra
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan:
          clean_workspace: true
          jobs:
            repo:
              tasks: *repo_plan
      - deploy:
          clean_workspace: true
          jobs:
            repo:
              resources:
                - docker
              tasks: *repo_deploy_tasks
            test_harness:
              resources:
                - docker
              tasks: *test_harness_deploy_tasks
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks test

  "prm-mhs-infra.test":
    group: mhs
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      dev_env:
        pipeline: prm-mhs-infra.dev
        stage: test
      mhs_docker:
        pipeline: prm-repo-mhs
        stage: build_docker
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: deploy_test
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - fetch:
                pipeline: prm-repo-mhs
                stage: build_docker
                job: outbound
                source: imagerc/outbound
                destination: prm-mhs-infra/imagerc
                is_file: true
            - exec:
                command: /bin/bash
                working_directory: prm-mhs-infra
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan:
          clean_workspace: true
          jobs:
            repo:
              tasks: *repo_plan
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *repo_deploy_tasks
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks test
  "prm-mhs-infra.pre-prod":
    group: mhs
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      test_env:
        pipeline: prm-mhs-infra.test
        stage: test
      mhs_docker:
        pipeline: prm-repo-mhs
        stage: build_docker
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: deploy_pre_prod
    environment_variables:
      NHS_ENVIRONMENT: pre-prod
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - fetch:
                pipeline: prm-repo-mhs
                stage: build_docker
                job: outbound
                source: imagerc/outbound
                destination: prm-mhs-infra/imagerc
                is_file: true
            - exec:
                command: /bin/bash
                working_directory: prm-mhs-infra
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan:
          clean_workspace: true
          jobs:
            repo:
              tasks: *repo_plan
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *repo_deploy_tasks
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks test
  "prm-mhs-infra.prod":
    group: mhs
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      pre-prod_env:
        pipeline: prm-mhs-infra.pre-prod
        stage: test
      mhs_docker:
        pipeline: prm-repo-mhs
        stage: build_docker
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: deploy_prod
    environment_variables:
      NHS_ENVIRONMENT: prod
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - fetch:
                pipeline: prm-repo-mhs
                stage: build_docker
                job: outbound
                source: imagerc/outbound
                destination: prm-mhs-infra/imagerc
                is_file: true
            - exec:
                command: /bin/bash
                working_directory: prm-mhs-infra
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan:
          clean_workspace: true
          jobs:
            repo:
              tasks: *repo_plan
      - deploy:
          approval:
            type: manual
            allow_only_on_success: true
          clean_workspace: true
          jobs:
            deploy: *repo_deploy_tasks
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks test
