format_version: 4
common:
  deploy_tasks: &deploy_tasks
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks generate_certs
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks upload_certs
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks tf_plan create
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks tf_apply

pipelines:
  "prm-mhs-infra-opentest":
    group: mhs
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      integration_adaptors:
        git: https://github.com/nhsconnect/prm-deductions-integration-adaptors.git
        branch: deductions
        destination: integration-adaptors
      docker:
        pipeline: mhs-docker-images
        stage: build
      docker_dns_images:
        pipeline: mhs-dns-images
        stage: test
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: check_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy:
              resources:
                - docker
              tasks: *deploy_tasks
      - wait_dns:
          clean_workspace: true
          resources:
            - dev
            - mhs
          tasks:
            - exec:
                command: /bin/bash
                working_directory: prm-mhs-infra
                arguments:
                  - -c
                  - ./tasks wait_for_dns
      - test:
          clean_workspace: true
          jobs:
            dns:
              resources:
                - dev
                - mhs
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks test_dns

  "prm-mhs-infra-ptl-integration":
    group: mhs
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      integration_adaptors:
        git: https://github.com/nhsconnect/prm-deductions-integration-adaptors.git
        branch: deductions
        destination: integration-adaptors
      system_integration:
        git: https://github.com/nhsconnect/prm-deductions-mhs-system-integration.git
        destination: system-integration
      docker:
        pipeline: mhs-docker-images
        stage: build
      docker_dns_images:
        pipeline: mhs-dns-images
        stage: test
      dev_env:
        pipeline: prm-mhs-infra-opentest
        stage: test
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy:
              resources:
                - docker
              tasks:
                - *deploy_tasks
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks nlb_ips create
      - wait_dns:
          clean_workspace: true
          resources:
            - test
            - mhs
          tasks:
            - exec:
                command: /bin/bash
                working_directory: prm-mhs-infra
                arguments:
                  - -c
                  - ./tasks wait_for_dns
      - test:
          clean_workspace: true
          jobs:
            functional-tests:
              resources:
                - test
                - mhs
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: system-integration
                    arguments:
                      - -c
                      - ./tasks functional_tests
            dns:
              resources:
                - test
                - mhs
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks test_dns
