format_version: 4
common:
  plan: &plan
    resources:
      - docker
    artifacts:
      - build:
          source: prm-mhs-infra/terraform/deployment.tfplan
          destination: prm-mhs-infra/terraform/
    tasks:
      - fetch:
          pipeline: prm-repo-mhs
          stage: import_docker
          job: outbound
          source: imagerc/outbound
          destination: prm-mhs-infra/imagerc
          is_file: true
      - exec:
          command: /bin/bash
          working_directory: prm-mhs-infra
          arguments:
            - -c
            - ./tasks tf_plan_repo create

  deploy: &deploy
    resources:
      - docker
    tasks:
      - fetch:
          pipeline: prm-repo-mhs
          stage: import_docker
          job: outbound
          source: imagerc/outbound
          destination: prm-mhs-infra/imagerc
          is_file: true
      - fetch:
          stage: plan
          job: plan
          source: prm-mhs-infra/terraform/deployment.tfplan
          destination: prm-mhs-infra/terraform/
          is_file: yes
      - exec:
          command: /bin/bash
          working_directory: prm-mhs-infra
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          working_directory: prm-mhs-infra
          arguments:
            - -c
            - ./tasks wait_ecs repo

  test_harness_deploy: &test_harness_deploy
    resources:
      - docker
    tasks:
      - fetch:
          pipeline: prm-repo-mhs
          stage: import_docker
          job: outbound
          source: imagerc/outbound
          destination: prm-mhs-infra/imagerc
          is_file: true
      - exec:
          command: /bin/bash
          working_directory: prm-mhs-infra
          arguments:
            - -c
            - ./tasks tf_plan_test_harness create
      - exec:
          command: /bin/bash
          working_directory: prm-mhs-infra
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          working_directory: prm-mhs-infra
          arguments:
            - -c
            - ./tasks wait_ecs test_harness

pipelines:
  "prm-mhs-infra.dev":
    group: mhs
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      mhs_docker:
        pipeline: prm-repo-mhs
        stage: import_docker
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: deploy_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - fetch:
                pipeline: prm-repo-mhs
                stage: import_docker
                job: outbound
                source: imagerc/outbound
                destination: prm-mhs-infra/imagerc
                is_file: true
            - exec:
                command: /bin/bash
                working_directory: prm-mhs-infra
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan:
          clean_workspace: true
          jobs:
            plan: *plan
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy
            test_harness: *test_harness_deploy
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks test
  "prm-mhs-infra.test":
    group: mhs
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      dev_env:
        pipeline: prm-mhs-infra.dev
        stage: test
      mhs_docker:
        pipeline: prm-repo-mhs
        stage: import_docker
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: deploy_test
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - fetch:
                pipeline: prm-repo-mhs
                stage: import_docker
                job: outbound
                source: imagerc/outbound
                destination: prm-mhs-infra/imagerc
                is_file: true
            - exec:
                command: /bin/bash
                working_directory: prm-mhs-infra
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan:
          clean_workspace: true
          jobs:
            plan: *plan
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks test
  "prm-mhs-infra.perf":
    group: mhs
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      test_env:
        pipeline: prm-mhs-infra.test
        stage: test
      mhs_docker:
        pipeline: prm-repo-mhs
        stage: import_docker
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: deploy_perf
    environment_variables:
      NHS_ENVIRONMENT: perf
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - fetch:
                pipeline: prm-repo-mhs
                stage: import_docker
                job: outbound
                source: imagerc/outbound
                destination: prm-mhs-infra/imagerc
                is_file: true
            - exec:
                command: /bin/bash
                working_directory: prm-mhs-infra
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan:
          clean_workspace: true
          jobs:
            plan: *plan
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy
  "prm-mhs-infra.pre-prod":
    group: mhs
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      test_env:
        pipeline: prm-mhs-infra.test
        stage: test
      mhs_docker:
        pipeline: prm-repo-mhs
        stage: import_docker
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: deploy_pre_prod
    environment_variables:
      NHS_ENVIRONMENT: pre-prod
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - fetch:
                pipeline: prm-repo-mhs
                stage: import_docker
                job: outbound
                source: imagerc/outbound
                destination: prm-mhs-infra/imagerc
                is_file: true
            - exec:
                command: /bin/bash
                working_directory: prm-mhs-infra
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan:
          clean_workspace: true
          jobs:
            plan: *plan
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks test
  "prm-mhs-infra.prod":
    group: mhs
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      pre-prod_env:
        pipeline: prm-mhs-infra.pre-prod
        stage: test
      mhs_docker:
        pipeline: prm-repo-mhs
        stage: import_docker
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: deploy_prod
    environment_variables:
      NHS_ENVIRONMENT: prod
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - fetch:
                pipeline: prm-repo-mhs
                stage: import_docker
                job: outbound
                source: imagerc/outbound
                destination: prm-mhs-infra/imagerc
                is_file: true
            - exec:
                command: /bin/bash
                working_directory: prm-mhs-infra
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan:
          clean_workspace: true
          jobs:
            plan: *plan
      - deploy:
          approval:
            type: manual
            allow_only_on_success: true
          clean_workspace: true
          jobs:
            deploy: *deploy
#      - test:
#          skipped: true
#          clean_workspace: true
#          jobs:
#            test:
#              resources:
#                - docker
#              tasks:
#                - exec:
#                    command: /bin/bash
#                    working_directory: prm-mhs-infra
#                    arguments:
#                      - -c
#                      - ./tasks test
