format_version: 4
common:
  repo_deploy_tasks: &repo_deploy_tasks
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks tf_plan_repo create
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks tf_apply
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks wait_ecs repo

  test_harness_deploy_tasks: &test_harness_deploy_tasks
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks tf_plan_test_harness create
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks tf_apply
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks wait_ecs test_harness

pipelines:
  "prm-mhs-infra-opentest":
    group: mhs
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      integration_adaptors:
        git: https://github.com/nhsconnect/prm-deductions-integration-adaptors.git
        branch: deductions
        destination: integration-adaptors
      docker:
        pipeline: mhs-docker-images
        stage: build
      mhs_docker:
        pipeline: prm-repo-mhs
        stage: build_docker
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: wait_dns_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - deploy:
          clean_workspace: true
          jobs:
            repo:
              resources:
                - docker
              tasks: *repo_deploy_tasks
            test_harness:
              resources:
                - docker
              tasks: *test_harness_deploy_tasks
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks test

  "prm-mhs-infra-ptl-integration":
    group: mhs
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      integration_adaptors:
        git: https://github.com/nhsconnect/prm-deductions-integration-adaptors.git
        branch: deductions
        destination: integration-adaptors
      system_integration:
        git: https://github.com/nhsconnect/prm-deductions-mhs-system-integration.git
        destination: system-integration
      docker:
        pipeline: mhs-docker-images
        stage: build
      dev_env:
        pipeline: prm-mhs-infra-opentest
        stage: test
      mhs_docker:
        pipeline: prm-repo-mhs
        stage: build_docker
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: wait_dns_test
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - deploy:
          clean_workspace: true
          jobs:
            deploy:
              resources:
                - docker
              tasks:
                - *repo_deploy_tasks
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks test
